# Generated by Django 4.2.1 on 2023-05-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("discriptions", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="portfolio/images/")),
                ("url", models.URLField(blank=True)),
            ],
        ),
    ]
